"""Sweep bucket_size at N values typical for cipher-maps.

Run once; save results to .claude/SWEEP_BUCKET_SIZE.md.
"""
from __future__ import annotations

import math
import time
from typing import Iterable

import phobic


def gen_keys(n: int) -> list[bytes]:
    # 16-byte keys mimic cipher-maps' HMAC-SHA256-truncated cipher_key shape.
    import os
    rng = os.urandom
    return [rng(16) for _ in range(n)]


def time_build(keys: list[bytes], bucket_size: int | None, repeats: int = 3,
               seed: int = 0xC1FE) -> tuple[float, float, int]:
    """Return (median_build_seconds, bits_per_key, range_size).

    Tries the given bucket_size in non-strict mode so unbuildable configs
    return a (probably high-collision) result instead of raising.
    """
    times: list[float] = []
    bpk = 0.0
    rs = 0
    for r in range(repeats):
        t0 = time.perf_counter()
        try:
            phf = phobic.build(
                keys, bucket_size=bucket_size, seed=seed + r,
                strict=False, max_retries=20,
            )
        except RuntimeError:
            return (float("inf"), float("nan"), 0)
        t1 = time.perf_counter()
        times.append(t1 - t0)
        bpk = phf.bits_per_key
        rs = phf.range_size
        if not phf.is_perfect:
            # Treat any non-perfect build as a fail at this config.
            return (float("inf"), float("nan"), 0)
    times.sort()
    return (times[len(times) // 2], bpk, rs)


def time_query(keys: list[bytes], bucket_size: int | None,
               sample: int = 5000, seed: int = 0xC1FE) -> float:
    """Return median ns per query (batch path)."""
    phf = phobic.build(
        keys, bucket_size=bucket_size, seed=seed,
        strict=True, max_retries=50,
    )
    sample_keys = keys[:sample]
    # Warm up.
    phf.lookup(sample_keys)
    runs = []
    for _ in range(5):
        t0 = time.perf_counter_ns()
        phf.lookup(sample_keys)
        t1 = time.perf_counter_ns()
        runs.append((t1 - t0) / sample)
    runs.sort()
    return runs[len(runs) // 2]


def sweep(n_values: Iterable[int], bucket_sizes: Iterable[int]) -> None:
    print("# bucket_size sweep results\n")
    print("Generated by .claude/sweep_bucket_size.py.")
    print("Build is non-strict, max_retries=20, seed varied across 3 reps; ")
    print("median wall time. Query is the C batch path on a 5K-key sample, ")
    print("median over 5 runs. Inf means the configuration could not produce a ")
    print("perfect build within the retry budget at the chosen seed.\n")
    for n in n_values:
        keys = gen_keys(n)
        auto = max(1, math.ceil(math.log2(n)))
        print(f"## N = {n:,} (auto bucket_size = {auto})\n")
        print("| bucket_size | build (ms) | bits/key | range/keys | query (ns) |")
        print("|------------:|-----------:|---------:|-----------:|-----------:|")
        rows = []
        for bs in bucket_sizes:
            build_s, bpk, rs = time_build(keys, bs)
            if math.isinf(build_s):
                rows.append((bs, "FAILED", "-", "-", "-"))
                continue
            qns = time_query(keys, bs)
            rows.append(
                (bs, f"{build_s * 1000:8.2f}", f"{bpk:5.2f}",
                 f"{rs / n:6.3f}", f"{qns:6.1f}")
            )
        # Also measure the auto default for comparison.
        build_s, bpk, rs = time_build(keys, None)
        if math.isinf(build_s):
            rows.append(("auto", "FAILED", "-", "-", "-"))
        else:
            qns = time_query(keys, None)
            rows.append(
                ("auto", f"{build_s * 1000:8.2f}", f"{bpk:5.2f}",
                 f"{rs / n:6.3f}", f"{qns:6.1f}")
            )
        for r in rows:
            print(f"| {r[0]:>11} | {r[1]:>10} | {r[2]:>8} | {r[3]:>10} | {r[4]:>10} |")
        print()


if __name__ == "__main__":
    sweep(
        n_values=[1_000, 10_000, 100_000],
        bucket_sizes=[2, 3, 4, 5, 6, 8, 10, 12, 14],
    )
