"""phobic 0.3.0 benchmark sweep.

Sweeps N x num_threads across the realistic operating range.
For each combination measures:
  - build wall time (median of REPS at small N; one rep at 10M)
  - resulting bits/key (deterministic; once)
  - num_shards picked by the auto heuristic
  - batch lookup wall time at threads=1 vs threads=N_THREADS_MAX
Then compares against 0.2.0 numbers and prints a recommendation.
"""
from __future__ import annotations

import gc
import math
import os
import time

import phobic


N_SWEEP = [1_000, 100_000, 1_000_000, 10_000_000]
THREAD_SWEEP = [1, 4, 8, 12]
BATCH_THREADS_FOR_QUERY = [1, 8]


def gen_keys(n: int) -> list[bytes]:
    """16-byte uniformly random keys. Mirrors cipher-maps' HMAC-SHA256-derived
    cipher_key shape; representative of "very large set" workloads."""
    return [os.urandom(16) for _ in range(n)]


def median_build(keys: list[bytes], num_threads: int, reps: int,
                 seed_base: int = 0xC0FE) -> tuple[float, float, int]:
    """Returns (median_build_seconds, bits_per_key, num_shards)."""
    times = []
    bpk = 0.0
    nshards = 0
    for r in range(reps):
        gc.collect()
        t0 = time.perf_counter()
        phf = phobic.build(keys, seed=seed_base + r, num_threads=num_threads)
        t1 = time.perf_counter()
        times.append(t1 - t0)
        bpk = phf.bits_per_key
        nshards = phf.num_shards
    times.sort()
    return times[len(times) // 2], bpk, nshards


def time_batch_query(phf: phobic.PHF, keys: list[bytes],
                      num_threads: int, reps: int = 5) -> float:
    """Return median ns per key for batch query."""
    runs = []
    for _ in range(reps):
        gc.collect()
        t0 = time.perf_counter_ns()
        phf.lookup(keys, num_threads=num_threads)
        t1 = time.perf_counter_ns()
        runs.append((t1 - t0) / len(keys))
    runs.sort()
    return runs[len(runs) // 2]


def run_one_n(n: int, build_reps: int, query_sample: int):
    print(f"\n## N = {n:,}")
    keys = gen_keys(n)

    # Build phase
    print(f"\n### build (median of {build_reps} reps; bpk and num_shards from one)\n")
    print("| num_threads | build (s) | bpk  | num_shards |")
    print("|------------:|----------:|-----:|-----------:|")
    last_phf = None
    for nt in THREAD_SWEEP:
        bt, bpk, ns = median_build(keys, nt, build_reps)
        print(f"| {nt:>11} | {bt:9.3f} | {bpk:4.2f} | {ns:>10} |")
        # Keep one PHF for the query bench (the threads=8 case)
        if nt == 8:
            last_phf = phobic.build(keys, seed=42, num_threads=8)
    if last_phf is None:
        last_phf = phobic.build(keys, seed=42, num_threads=8)

    # Batch query phase
    sample_keys = keys[:query_sample] if len(keys) > query_sample else keys
    print(f"\n### batch query ({len(sample_keys):,} keys, median of 5 reps)\n")
    print("| num_threads | ns/key |")
    print("|------------:|-------:|")
    for nt in BATCH_THREADS_FOR_QUERY:
        ns_per_key = time_batch_query(last_phf, sample_keys, nt)
        print(f"| {nt:>11} | {ns_per_key:6.1f} |")

    return None


def main():
    print("# phobic 0.3.0 benchmark sweep\n")
    print(f"Generated by .claude/sweep_0_3_0.py on a {os.cpu_count()}-core machine.")
    print("Build is `phobic.build(...)` with default load_factor=0.5; ")
    print("auto num_shards. All keys are 16 random bytes (cipher-maps shape).")
    print("Median build time across reps; query is the C batch path. ")
    print("Wall-clock numbers are illustrative; absolute values vary by CPU.\n")

    # Build reps schedule: smaller N gets more reps for stability.
    schedule = [
        (1_000,        5,  1_000),
        (100_000,      3,  10_000),
        (1_000_000,    3,  50_000),
        (10_000_000,   1,  50_000),
    ]
    for n, reps, qs in schedule:
        run_one_n(n, reps, qs)


if __name__ == "__main__":
    main()
